### ISSUE TITLE
Episode image not showing in Apple Podcast

### ISSUE THREAD

**Issue by mortenkjarulff** [frjo/hugo-theme-zen#51]
Hi,

It seems my episode image is not showing in Apple Podcast:
https://podcasts.apple.com/us/podcast/regnormen-keld/id1608769069?i=1000550196773
It shows my shows image?
Same in app on iphone and ipad.

Works fine on Spotify:
https://open.spotify.com/episode/1l6UPdxDhZnSNxaXFCZuAV

Can anyone see if and what I did wrong?

https://gitlab.com/mortenkjarulff/gitte2
https://gitte.one/podcast/index.xml

/Morten

**Comment by frjo** [comment]
Take a look at https://podba.se/validate/?url=https://gitte.one/podcast/index.xml. Might give you some hint.

I also noticed that the feed is missing the start xml tag "<?xml version="1.0" encoding="UTF-8"?>". I have corrected this in the Zen repo now.

**Comment by mortenkjarulff** [comment]
Dont think that xml change is good

![image](https://user-images.githubusercontent.com/32191001/152802515-f4003dfe-e7f3-49e3-8b9d-562dbbd2075d.png)

![image](https://user-images.githubusercontent.com/32191001/152802593-d46c6346-fdd8-467d-a720-16d0a6d37fe2.png)

Morten

**Comment by frjo** [comment]
Realising that you are using the 2.x branch, was slow in pushing this change there. Fixed now.

**Comment by mortenkjarulff** [comment]
Yes, using 2.x, should have said that.
Have updated to latest.
Feed is working now.
Have redone both cover and episode image.

It seems Apple Podcast still don't show the episode image.
Will give it some time and see if it updates.

**Comment by mortenkjarulff** [comment]
Anyone has an example of a show in Apple Podcast that has an episode image other than the cover image?
I can't find any, so maybe Apple Podcast simply does not show it?

**Comment by mortenkjarulff** [comment]
After renaming the episode image multiple times and/or after adding a second episode, Apple Podcast is showing correct episode image in a browser, but not in the app on my ipad.

Google Podcast has also found my podcast, but is now behind (just added second episode and some text updates).

So I guess both my images and the feed is fine, I just have to be patient.

**Comment by mortenkjarulff** [comment]
According to this
https://www.podcasthelpdesk.com/podcast-episdodic-artwork-test-results-phd-130/?utm_source=podnews.net&utm_medium=web&utm_campaign=podnews.net:2020-03-12
Episode image is not shown in Apple Podcast app on iOS and also not in Google Podcast.
This is also what I see, so all fine.
